### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by mikeerickson** [sourceboat/sass-lint-vue#2]
Hey There

Not sure if this is still an active project, but I figured I would pass along this info (I have received same error running within project, or globally)  

NOTE:  If you are not keep to "fix" these issues, please let me know and I will fork and fix for internally use if anything else :-)

```
$ sass-lint-vue src
```

produces the following 

```
/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:89
                if(elems[i].children.length > 0){
                                    ^

TypeError: Cannot read property 'length' of undefined
    at findAll (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:89:23)
    at findAll (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:90:27)
    at Object.findAll (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:90:27)
    at selectAll (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/css-select/index.js:26:70)
    at select (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/css-select/index.js:21:10)
    at CSSselect (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/css-select/index.js:41:9)
    at initialize.exports.find (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/cheerio/lib/api/traversing.js:40:21)
    at initialize.module.exports (/Users/mikee/.nvm/versions/node/v6.8.1/lib/node_modules/sass-lint-vue/node_modules/cheerio/lib/cheerio.js:86:18)
```

**Comment by pehbehbeh** [comment]
Hi @mikeerickson, thanks for submitting this error. This is an active project. 😉 

I can get into it by the end of the week.

If you already have the solution, you could make a PR?

**Comment by mikeerickson** [comment]
@pehbehbeh I don't have a solution as of yet, I just shelved it for a bit while I await your reply.  If you don't have a solution by the time I get back to it, I will submit a PR

**Comment by FPierre** [comment]
Same issue here:

```
$ sass-lint-vue src/components/LayoutFooter.vue 

/usr/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:89
                if(elems[i].children.length > 0){
TypeError: Cannot read property 'length' of undefined
    at Object.findAll (/usr/lib/node_modules/sass-lint-vue/node_modules/domutils/lib/querying.js:89:23)
    at selectAll (/usr/lib/node_modules/sass-lint-vue/node_modules/css-select/index.js:26:70)
    at select (/usr/lib/node_modules/sass-lint-vue/node_modules/css-select/index.js:21:10)
    at CSSselect (/usr/lib/node_modules/sass-lint-vue/node_modules/css-select/index.js:41:9)
    at initialize.exports.find (/usr/lib/node_modules/sass-lint-vue/node_modules/cheerio/lib/api/traversing.js:40:21)
    at initialize.module.exports (/usr/lib/node_modules/sass-lint-vue/node_modules/cheerio/lib/cheerio.js:86:18)
    at new initialize (/usr/lib/node_modules/sass-lint-vue/node_modules/cheerio/lib/static.js:29:20)
    at initialize (/usr/lib/node_modules/sass-lint-vue/node_modules/cheerio/lib/static.js:26:14)
    at DefaultHandler.htmlparser.DefaultHandler [as _callback] (/usr/lib/node_modules/sass-lint-vue/lib/linter.js:73:24)
    at DefaultHandler$handleCallback [as handleCallback] (/usr/lib/node_modules/sass-lint-vue/node_modules/htmlparser/lib/htmlparser.js:644:9)
```

It's coming from [domutils package](https://github.com/fb55/domutils/blob/8e0f72553aa19a9177668f1507f8eb82129bdd61/lib/querying.js#L83) (`findAll` function).

**Comment by pehbehbeh** [comment]
@FPierre Could you post your `src/components/LayoutFooter.vue` file?

@mikeerickson Maybe you can also post your example file(s) for future reference?

**Comment by FPierre** [comment]
`LayoutFooter.vue` is almost 200 lines of codes. I cut parts.

* It uses Bootstrap v4 alpha6
* Pug
* SASS
* Vue.js 2.2.2 

```
<template lang='pug'>
.layout-footer-component
  .desktop.hidden-sm-down
    footer
      .container
        .row
          .col
            estimate-button

          .col
            // Pug code here...
</template>

// Here 
<script src='//url-to-my-external-script.min.js'></script>
<script>
import EstimateButton from './EstimateButton'

export default {
  components: {
    EstimateButton
  }
}
</script>

<style lang='scss' scoped>
// Call SASS variables and functions files
@import '~styles/_variables.scss';
@import '~styles/resources.scss';

.layout-footer-component {
  background-color: $gray;
  color: $white;
  font: {
    size: .8rem;
  };

  a {
    color: inherit;
  }

  footer {
    padding: {
      bottom: 1rem;
      top: 1rem;
    };
  }

  ul {
    list-style: none;
    padding-left: 0;
  }

  .column-title {
    display: block;
    font: {
      family: 'GothamMedium', sans-serif;
      size: .9rem;
    };
    margin-bottom: 1rem;
    text-transform: uppercase;
  }

  .contacts {
    .fa-youtube {
      margin-left: .6rem;
    }

    .phone {
      font-family: 'GothamBold', sans-serif;
    }

    .form-link {
      text-decoration: underline;
    }
  }
}
</style>
```
